import type {Language} from "../types";

export const LANGUAGES: Language[] = [
  {name: "Afrikaans", nativeName: "Afrikaans", flag: "🇿🇦", speech: "af-ZA", tts: "af-ZA"},
  {name: "Albanian", nativeName: "Shqip", flag: "🇦🇱", speech: "sq-AL", tts: "sq-AL"},
  {name: "Amharic", nativeName: "አማርኛ", flag: "🇪🇹", speech: "am-ET", tts: "am-ET"},
  {name: "Arabic", nativeName: "العربية", flag: "🇸🇦", speech: "ar-SA", tts: "ar-SA"},
  {name: "Armenian", nativeName: "Հայերեն", flag: "🇦🇲", speech: "hy-AM", tts: "hy-AM"},
  {name: "Azerbaijani", nativeName: "Azərbaycanca", flag: "🇦🇿", speech: "az-AZ", tts: "az-AZ"},
  {name: "Bengali", nativeName: "বাংলা", flag: "🇧🇩", speech: "bn-BD", tts: "bn-BD"},
  {name: "Bosnian", nativeName: "Bosanski", flag: "🇧🇦", speech: "bs-BA", tts: "bs-BA"},
  {name: "Bulgarian", nativeName: "Български", flag: "🇧🇬", speech: "bg-BG", tts: "bg-BG"},
  {name: "Burmese", nativeName: "မြန်မာ", flag: "🇲🇲", speech: "my-MM", tts: "my-MM"},
  {name: "Catalan", nativeName: "Català", flag: "🇪🇸", speech: "ca-ES", tts: "ca-ES"},
  {name: "Chinese (Simplified)", nativeName: "简体中文", flag: "🇨🇳", speech: "zh-CN", tts: "zh-CN"},
  {name: "Croatian", nativeName: "Hrvatski", flag: "🇭🇷", speech: "hr-HR", tts: "hr-HR"},
  {name: "Czech", nativeName: "Čeština", flag: "🇨🇿", speech: "cs-CZ", tts: "cs-CZ"},
  {name: "Danish", nativeName: "Dansk", flag: "🇩🇰", speech: "da-DK", tts: "da-DK"},
  {name: "Dutch", nativeName: "Nederlands", flag: "🇳🇱", speech: "nl-NL", tts: "nl-NL"},
  {name: "English", nativeName: "English", flag: "🇬🇧", speech: "en-US", tts: "en-US"},
  {name: "Estonian", nativeName: "Eesti", flag: "🇪🇪", speech: "et-EE", tts: "et-EE"},
  {name: "Filipino", nativeName: "Filipino", flag: "🇵🇭", speech: "fil-PH", tts: "fil-PH"},
  {name: "Finnish", nativeName: "Suomi", flag: "🇫🇮", speech: "fi-FI", tts: "fi-FI"},
  {name: "French", nativeName: "Français", flag: "🇫🇷", speech: "fr-FR", tts: "fr-FR"},
  {name: "Georgian", nativeName: "ქართული", flag: "🇬🇪", speech: "ka-GE", tts: "ka-GE"},
  {name: "German", nativeName: "Deutsch", flag: "🇩🇪", speech: "de-DE", tts: "de-DE"},
  {name: "Greek", nativeName: "Ελληνικά", flag: "🇬🇷", speech: "el-GR", tts: "el-GR"},
  {name: "Hebrew", nativeName: "עברית", flag: "🇮🇱", speech: "he-IL", tts: "he-IL"},
  {name: "Hindi", nativeName: "हिन्दी", flag: "🇮🇳", speech: "hi-IN", tts: "hi-IN"},
  {name: "Hungarian", nativeName: "Magyar", flag: "🇭🇺", speech: "hu-HU", tts: "hu-HU"},
  {name: "Icelandic", nativeName: "Íslenska", flag: "🇮🇸", speech: "is-IS", tts: "is-IS"},
  {name: "Indonesian", nativeName: "Bahasa Indonesia", flag: "🇮🇩", speech: "id-ID", tts: "id-ID"},
  {name: "Irish", nativeName: "Gaeilge", flag: "🇮🇪", speech: "ga-IE", tts: "ga-IE"},
  {name: "Italian", nativeName: "Italiano", flag: "🇮🇹", speech: "it-IT", tts: "it-IT"},
  {name: "Japanese", nativeName: "日本語", flag: "🇯🇵", speech: "ja-JP", tts: "ja-JP"},
  {name: "Kazakh", nativeName: "Қазақша", flag: "🇰🇿", speech: "kk-KZ", tts: "kk-KZ"},
  {name: "Khmer", nativeName: "ខ្មែរ", flag: "🇰🇭", speech: "km-KH", tts: "km-KH"},
  {name: "Korean", nativeName: "한국어", flag: "🇰🇷", speech: "ko-KR", tts: "ko-KR"},
  {name: "Lao", nativeName: "ລາວ", flag: "🇱🇦", speech: "lo-LA", tts: "lo-LA"},
  {name: "Latvian", nativeName: "Latviešu", flag: "🇱🇻", speech: "lv-LV", tts: "lv-LV"},
  {name: "Lithuanian", nativeName: "Lietuvių", flag: "🇱🇹", speech: "lt-LT", tts: "lt-LT"},
  {name: "Macedonian", nativeName: "Македонски", flag: "🇲🇰", speech: "mk-MK", tts: "mk-MK"},
  {name: "Malay", nativeName: "Bahasa Melayu", flag: "🇲🇾", speech: "ms-MY", tts: "ms-MY"},
  {name: "Mongolian", nativeName: "Монгол", flag: "🇲🇳", speech: "mn-MN", tts: "mn-MN"},
  {name: "Norwegian", nativeName: "Norsk", flag: "🇳🇴", speech: "nb-NO", tts: "nb-NO"},
  {name: "Persian", nativeName: "فارسی", flag: "🇮🇷", speech: "fa-IR", tts: "fa-IR"},
  {name: "Polish", nativeName: "Polski", flag: "🇵🇱", speech: "pl-PL", tts: "pl-PL"},
  {name: "Portuguese", nativeName: "Português", flag: "🇵🇹", speech: "pt-PT", tts: "pt-PT"},
  {name: "Romanian", nativeName: "Română", flag: "🇷🇴", speech: "ro-RO", tts: "ro-RO"},
  {name: "Russian", nativeName: "Русский", flag: "🇷🇺", speech: "ru-RU", tts: "ru-RU"},
  {name: "Serbian", nativeName: "Српски", flag: "🇷🇸", speech: "sr-RS", tts: "sr-RS"},
  {name: "Slovak", nativeName: "Slovenčina", flag: "🇸🇰", speech: "sk-SK", tts: "sk-SK"},
  {name: "Slovenian", nativeName: "Slovenščina", flag: "🇸🇮", speech: "sl-SI", tts: "sl-SI"},
  {name: "Spanish", nativeName: "Español", flag: "🇪🇸", speech: "es-ES", tts: "es-ES"},
  {name: "Swahili", nativeName: "Kiswahili", flag: "🇹🇿", speech: "sw-TZ", tts: "sw-TZ"},
  {name: "Swedish", nativeName: "Svenska", flag: "🇸🇪", speech: "sv-SE", tts: "sv-SE"},
  {name: "Tamil", nativeName: "தமிழ்", flag: "🇮🇳", speech: "ta-IN", tts: "ta-IN"},
  {name: "Telugu", nativeName: "తెలుగు", flag: "🇮🇳", speech: "te-IN", tts: "te-IN"},
  {name: "Thai", nativeName: "ไทย", flag: "🇹🇭", speech: "th-TH", tts: "th-TH"},
  {name: "Turkish", nativeName: "Türkçe", flag: "🇹🇷", speech: "tr-TR", tts: "tr-TR"},
  {name: "Ukrainian", nativeName: "Українська", flag: "🇺🇦", speech: "uk-UA", tts: "uk-UA"},
  {name: "Urdu", nativeName: "اردو", flag: "🇵🇰", speech: "ur-PK", tts: "ur-PK"},
  {name: "Uzbek", nativeName: "O‘zbekcha", flag: "🇺🇿", speech: "uz-UZ", tts: "uz-UZ"},
  {name: "Vietnamese", nativeName: "Tiếng Việt", flag: "🇻🇳", speech: "vi-VN", tts: "vi-VN"},
];

export const DEFAULT_SOURCE_LANGUAGE =
  LANGUAGES.find(language => language.name === "Turkish") ?? LANGUAGES[0];
export const DEFAULT_TARGET_LANGUAGE =
  LANGUAGES.find(language => language.name === "Khmer") ?? LANGUAGES[1];
