import {LanguageRulePack} from "./types";

export const LANGUAGE_RULES: Record<string, LanguageRulePack> = {
  "af-ZA": {locale: "af-ZA", voiceFallbacks: ["af-ZA"]},
  "sq-AL": {locale: "sq-AL", voiceFallbacks: ["sq-AL"]},
  "am-ET": {locale: "am-ET", voiceFallbacks: ["am-ET"]},
  "ar-SA": {locale: "ar-SA", voiceFallbacks: ["ar-SA"]},
  "hy-AM": {locale: "hy-AM", voiceFallbacks: ["hy-AM"]},
  "az-AZ": {locale: "az-AZ", voiceFallbacks: ["az-AZ"]},
  "bn-BD": {locale: "bn-BD", voiceFallbacks: ["bn-BD"]},
  "bs-BA": {locale: "bs-BA", voiceFallbacks: ["bs-BA"]},
  "bg-BG": {locale: "bg-BG", voiceFallbacks: ["bg-BG"]},
  "my-MM": {locale: "my-MM", voiceFallbacks: ["my-MM"]},
  "ca-ES": {locale: "ca-ES", voiceFallbacks: ["ca-ES"]},
  "zh-CN": {locale: "zh-CN", voiceFallbacks: ["zh-CN"]},
  "hr-HR": {locale: "hr-HR", voiceFallbacks: ["hr-HR"]},
  "cs-CZ": {locale: "cs-CZ", voiceFallbacks: ["cs-CZ"]},
  "da-DK": {locale: "da-DK", voiceFallbacks: ["da-DK"]},
  "nl-NL": {locale: "nl-NL", voiceFallbacks: ["nl-NL"]},
  "en-US": {locale: "en-US", voiceFallbacks: ["en-US"]},
  "et-EE": {locale: "et-EE", voiceFallbacks: ["et-EE"]},
  "fil-PH": {locale: "fil-PH", voiceFallbacks: ["fil-PH"]},
  "fi-FI": {locale: "fi-FI", voiceFallbacks: ["fi-FI"]},
  "fr-FR": {locale: "fr-FR", voiceFallbacks: ["fr-FR"]},
  "ka-GE": {locale: "ka-GE", voiceFallbacks: ["ka-GE"]},
  "de-DE": {locale: "de-DE", voiceFallbacks: ["de-DE"]},
  "el-GR": {locale: "el-GR", voiceFallbacks: ["el-GR"]},
  "he-IL": {locale: "he-IL", voiceFallbacks: ["he-IL"]},
  "hi-IN": {locale: "hi-IN", voiceFallbacks: ["hi-IN"]},
  "hu-HU": {locale: "hu-HU", voiceFallbacks: ["hu-HU"]},
  "is-IS": {locale: "is-IS", voiceFallbacks: ["is-IS"]},
  "id-ID": {locale: "id-ID", voiceFallbacks: ["id-ID"]},
  "ga-IE": {locale: "ga-IE", voiceFallbacks: ["ga-IE"]},
  "it-IT": {locale: "it-IT", voiceFallbacks: ["it-IT"]},
  "ja-JP": {locale: "ja-JP", voiceFallbacks: ["ja-JP"]},
  "kk-KZ": {locale: "kk-KZ", voiceFallbacks: ["kk-KZ"]},
  "km-KH": {locale: "km-KH", voiceFallbacks: ["km-KH"]},
  "ko-KR": {locale: "ko-KR", voiceFallbacks: ["ko-KR"]},
  "lo-LA": {locale: "lo-LA", voiceFallbacks: ["lo-LA"]},
  "lv-LV": {locale: "lv-LV", voiceFallbacks: ["lv-LV"]},
  "lt-LT": {locale: "lt-LT", voiceFallbacks: ["lt-LT"]},
  "mk-MK": {locale: "mk-MK", voiceFallbacks: ["mk-MK"]},
  "ms-MY": {locale: "ms-MY", voiceFallbacks: ["ms-MY"]},
  "mn-MN": {locale: "mn-MN", voiceFallbacks: ["mn-MN"]},
  "nb-NO": {locale: "nb-NO", voiceFallbacks: ["nb-NO"]},
  "fa-IR": {locale: "fa-IR", voiceFallbacks: ["fa-IR"]},
  "pl-PL": {locale: "pl-PL", voiceFallbacks: ["pl-PL"]},
  "pt-PT": {locale: "pt-PT", voiceFallbacks: ["pt-PT"]},
  "ro-RO": {locale: "ro-RO", voiceFallbacks: ["ro-RO"]},
  "ru-RU": {locale: "ru-RU", voiceFallbacks: ["ru-RU"]},
  "sr-RS": {locale: "sr-RS", voiceFallbacks: ["sr-RS"]},
  "sk-SK": {locale: "sk-SK", voiceFallbacks: ["sk-SK"]},
  "sl-SI": {locale: "sl-SI", voiceFallbacks: ["sl-SI"]},
  "es-ES": {locale: "es-ES", voiceFallbacks: ["es-ES"]},
  "sw-TZ": {locale: "sw-TZ", voiceFallbacks: ["sw-TZ"]},
  "sv-SE": {locale: "sv-SE", voiceFallbacks: ["sv-SE"]},
  "ta-IN": {locale: "ta-IN", voiceFallbacks: ["ta-IN"]},
  "te-IN": {locale: "te-IN", voiceFallbacks: ["te-IN"]},
  "th-TH": {locale: "th-TH", voiceFallbacks: ["th-TH"]},
  "tr-TR": {locale: "tr-TR", voiceFallbacks: ["tr-TR"]},
  "uk-UA": {locale: "uk-UA", voiceFallbacks: ["uk-UA"]},
  "ur-PK": {locale: "ur-PK", voiceFallbacks: ["ur-PK"]},
  "uz-UZ": {locale: "uz-UZ", voiceFallbacks: ["uz-UZ"]},
  "vi-VN": {locale: "vi-VN", voiceFallbacks: ["vi-VN"]},
};

export function getLanguageRule(locale: string): LanguageRulePack {
  const exact = LANGUAGE_RULES[locale];
  if (exact) return exact;
  const prefix = String(locale || "").toLowerCase().split("-")[0];
  const key = Object.keys(LANGUAGE_RULES).find(item => item.toLowerCase().split("-")[0] === prefix);
  return key ? LANGUAGE_RULES[key] : {locale, voiceFallbacks: [locale]};
}
